# Generated by Django 2.2.5 on 2019-09-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0003_auto_20190906_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardcreate',
            name='user',
        ),
        migrations.AddField(
            model_name='cardcreate',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
